<section class="container">
    <header class="header">
      <h1> USERS TABLE</h1>
    </header>
    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Password</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>

    <?php
     

      foreach ($this->dot->get('data') as $key => $value):

     ?>
      
    <tr>
      <th scope="row"><?php echo $key + 1; ?></th>
      <td><?php echo $value['name']; ?></td>
      <td><?php echo $value['email']; ?></td>
      <td><?php echo $value['password']; ?></td>
      <td><a href="<?php echo URL;?>remove/<?php echo $value['id']; ?>">X</a></td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>
</section>